[tool.poetry]
name = "sumith-bot"
version = "0.1.0"
description = ""
authors = ["Sumith Shridhar"]

[tool.poetry.dependencies]
python = "^3.11"
praw = "*"
moviepy = "*"
requests = "*"
python-dotenv = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
